himalaya/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name="himalaya"

urlpatterns = [
    path('home/', views.homepage ,name="home"),
    path('home/authuser', views.authuser , name="login_signup"),
    path('home/login', views.loginuser , name="login"),
    path('home/signup', views.signup , name="signup"),
    path('home/tourism', views.tourismmain , name="tourism"),
    path('home/tourism/bilaspur', views.bilaspur , name="bilaspur"),
    path('home/tourism/chamba', views.chamba , name="chamba"),
    path('home/tourism/hamirpur', views.hamirpur , name="hamirpur"),
    path('home/tourism/kangra', views.kangra , name="kangra"),
    path('home/tourism/kinnaur', views.kinnaur , name="kinnaur"),
    path('home/tourism/kullu', views.kullu , name="kullu"),
    path('home/tourism/una', views.una , name="una"),
    path('home/tourism/mandi', views.mandi , name="mandi"),
    path('home/tourism/shimla', views.shimla , name="shimla"),
    path('home/tourism/lahual_spiti', views.lahual_spiti, name="lahual_spiti"),
    path('home/tourism/gettripplan', views.gettripplan , name="gettripplan"),
    path('home/tourism/tripplan', views.tripplanner , name="displaytripplan"),
    path('home/tourism/getweatherdata', views.getweatherdata , name="getweatherdata"),
    path('home/tourism/displayweatherdata', views.weatherdata, name="displayweather")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include("himalaya.urls"),name="main"),
    path('admin/', admin.site.urls),
]

himalaya/models.py
from django.db import models

# Create your models here.

himalaya/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta
import json
import urllib.request
import urllib.parse
import openai
# Create your views here.

user=forecast=None
errormsg1=errormsg2=tripplan=''

def homepage(request):
    return render(request,'himalaya/home.html',context={"user":user})

def tourismmain(request):
    if user!=None and user.is_authenticated:
        return render(request,"himalaya/tour.html",context={})
    return HttpResponseRedirect(reverse('himalaya:login_signup'))

def authuser(request):
    return render(request,'himalaya/login.html',context={"error_msg1":errormsg1,"error_msg2":errormsg2,})

def loginuser(request):
    global user,errormsg1
    username=request.POST['username']
    pwd=request.POST['password']
    print(username,pwd,user)
    user=authenticate(request,username=username,password=pwd)
    print(username,pwd,user)
    if user is not None:
        login(request=request,user=user)
        return HttpResponseRedirect(reverse('himalaya:home'))
    else:
        print("Login Insuccessful")
        errormsg1='Invalid Credentials'
        return HttpResponseRedirect(reverse('himalaya:login_signup'))    
    
def signup(request):
    global user,errormsg2
    uname=request.POST["name"]
    email=request.POST["email_id"]
    pwd=request.POST["passwd"]
    print(uname,email,pwd)
    try:
        tempuser = User.objects.create_user(uname,email,pwd)
        tempuser.first_name=uname
        user=tempuser
        login(request=request,user=user)
        return HttpResponseRedirect(reverse("himalaya:home")) 
    except:
        errormsg2="User name already exists"
        return HttpResponseRedirect(reverse("himalaya:login_signup"))

def getweatherdata(request):
    global forecast
    
    date=request.POST["date"]
    place=request.POST["place"]+",HP,INDIA"
    print(date,place)
    BaseURL = 'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/'

    ApiKey='SHLY7RWBEGPDMNY4R3T66QUX4'
    UnitGroup='us'
    
    Apiquery=BaseURL+place+"/"+date+"?"+"&unitGroup"+UnitGroup+"&key="+ApiKey
    try:
        req=urllib.request.urlopen(Apiquery)
    except:
        print("Not able to get data")
        return HttpResponseRedirect(reverse("himalaya:weather"))
    
    rawdata=req.read()
    req.close()
    forecast=json.loads(rawdata)
    
    return HttpResponseRedirect(reverse("himalaya:displayweather"))


def weatherdata(request):
    global forecast
    if user!=None and user.is_authenticated:
        
    
        currdate=timezone.now().strftime("%Y-%m-%d")
        maxdate=(timezone.now()+timedelta(days=15)).strftime("%Y-%m-%d")
        temp=days=None
        if forecast is not None:
            temp=forecast
            days=forecast['days'][0]
            forecast=None
        return render(request,"himalaya/weather.html",context={"forecast":temp,
                                                                "days":days,
                                                                "today":currdate,
                                                                "maxdate":maxdate,})
    else:
        return HttpResponseRedirect(reverse('himalaya:login_signup'))
    
def tripplanner(request):
    global tripplan
    if user!=None and user.is_authenticated:
        temp=None
        startdate=timezone.now().strftime("%Y-%m-%d")
        enddate=(timezone.now()+timedelta(120)).strftime("%Y-%m-%d")
        if tripplan!='':
            temp=tripplan
            tripplan=''
        return render(request,"himalaya/tripdetails.html",context={
            "tripplan":temp,
            "startdate":startdate,
            "enddate":enddate,
        })
    else:
        return HttpResponseRedirect(reverse('himalaya:login_signup'))
    
def gettripplan(request):
    global tripplan
    
    openai.api_key = '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'
    messages = [ {"role": "system", "content": 
                "You are a intelligent assistant."} ]
    date=request.POST['date']
    enddate=request.POST['enddate']
    place=request.POST['place']+',HP'
    print(date,enddate,place)
    message = "Create an iteniary for visiting "+place+" from "+date+" to "+enddate
    if message:
        messages.append(
            {"role": "user", "content": message},
        )
        chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=messages
        )
    reply = chat.choices[0].message.content
    tripplan= reply
    messages.append({"role": "assistant", "content": reply})
    return HttpResponseRedirect(reverse('himalaya:displaytripplan'))

def bilaspur(request):
    return render(request,"himalaya/bilaspur.html",context={})
def chamba(request):
    return render(request,"himalaya/chamba.html",context={})
def hamirpur(request):
    return render(request,"himalaya/hamirpur.html",context={})
def kangra(request):
    return render(request,"himalaya/kangra.html",context={})
def kinnaur(request):
    return render(request,"himalaya/kinnaur.html",context={})
def una(request):
    return render(request,"himalaya/una.html",context={})
def kullu(request):
    return render(request,"himalaya/kullu.html",context={})
def mandi(request):
    return render(request,"himalaya/mandi.html",context={})
def shimla(request):
    return render(request,"himalaya/shimla.html",context={})
def lahual_spiti(request):
    return render(request,'himalaya/lahual&spiti.html',context={})

himalaya/templates/himalaya/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visit Himalayas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
    crossorigin="anonymous">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css'>
    <link rel="stylesheet" href="{% static 'himalaya/home.css' %}">
</head>
<body>
    <section id="top">
        <img src="https://images.hdqwalls.com/download/mountain-range-blue-5k-yf-2560x1440.jpg" id="bg" />
        <h2 id="text">Himalayas</h2>
        <img src="{% static 'himalaya/Images/man.png' %}" id="man" />
        <img src="{% static 'himalaya/Images/clouds_1.png' %}" id="clouds_1" />
        <img src="{% static 'himalaya/Images/clouds_2.png' %}" id="clouds_2" />
        <!-- <img src="/Images/clouds_3.png" id="clouds_3" />
        <img src="/Images/clouds_4.png" id="clouds_4" /> -->
        <img src="{% static 'himalaya/Images/111.png' %}" id="mountain_left" />
        <img src="{% static 'himalaya/Images/222.png' %}" id="mountain_right" />
      </section>
    <section id="sec">
        <h2>Welcome to the Himalayas</h2>
        <p>
          The Himalayas offer some of the most breathtaking and dramatic landscapes on 
          Earth. Towering snow-capped peaks, deep valleys, pristine rivers, serene lakes,
           and lush forests create a mesmerizing natural scenery that appeals to nature 
           enthusiasts, hikers, and photographers. Mount Kailash, for instance, is 
           considered sacred in Hinduism, Buddhism, and Jainism. The region is dotted 
           with monasteries, temples, and shrines that draw pilgrims and tourists seeking 
           spiritual enlightenment and cultural experiences. Trekkers, mountaineers, and 
           climbers come here to test their skills and conquer some of the world's highest
            peaks, including Mount Everest. Activities like white-water rafting, 
            paragliding, and skiing also attract thrill-seekers.Festivals like Diwali, 
            Holi, Losar, and Dashain are celebrated with great fervor, allowing tourists 
            to immerse themselves in local traditions and festivities. The people of the 
            Himalayan region are known for their warmth and hospitality. Visitors often 
            find themselves welcomed into the homes of locals, allowing for authentic 
            cultural experiences and interactions.
          </p>
        </section>
        <footer>
          <a href="{% url 'himalaya:home' %}"><i class="fa-solid fa-house fa-xl"></i></a>
          <a href="{% url 'himalaya:displayweather' %}"><i class="fa-solid fa-cloud-sun-rain fa-xl"></i></a>
          <a href="{% url 'himalaya:tourism' %}"><i class="fa-solid fa-person-hiking fa-xl"></i></a>
          <a href="{% url 'himalaya:login_signup' %}"><i class="fa-solid fa-user fa-xl"></i></a>
        </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="{% static 'himalaya/home.js' %}"></script>
</body>
</html>

himalaya/templates/himalaya/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello<h1>{% if user %}<h2> {{ user.first_name }}</h2>{% else %}<h3>User</h3>{% endif %}
    
    
</body>
</html>

himalaya/templates/himalaya/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Signup</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
    crossorigin="anonymous">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css'>
    <link rel="stylesheet" href="{% static 'himalaya/login.css' %}">
</head>
<body>
  <div id="header">
    <div class="container" id="container">
      <div class="form-container sign-up-container">
        <form action="{% url 'himalaya:signup' %}" method="post">
          {% csrf_token %}
          <h1>Create Account</h1>
          <h1>{% if errormsg2 %} {{ errormsg2 }} {% endif %}</h1>
          <div class="social-container">
            <a href="#" class="social"><i class="fa-solid fa-person-skating"></i></a>
            <a href="#" class="social"><i class="fa-solid fa-person-skiing-nordic"></i></a>
            <a href="#" class="social"><i class="fa-solid fa-snowflake"></i></a>
          </div>
          <span>or use your email for registration</span>
          <input required type="text" placeholder="Username" name="name"/>
          <input required type="email" placeholder="Email" name="email_id"/>
          <input required type="password" placeholder="Password" name="passwd"/>
          <button type="submit">Sign Up</button>
        </form>
      </div>
      <div class="form-container sign-in-container">
        <form action="{% url 'himalaya:login' %}" method="POST">
          {% csrf_token %}
          <h1>Sign in</h1>
          <h1>{% if errormsg1 %} {{ errormsg1 }} {% endif %}</h1>
          <div class="social-container">
            <a href="#" class="social"><i class="fa-solid fa-person-hiking"></i></a>
            <a href="#" class="social"><i class="fa-solid fa-person-snowboarding"></i></a>
            <a href="#" class="social"><i class="fa-solid fa-person-skiing"></i></a>
          </div>
          <span>or use your account</span>
          <input required type="text" placeholder="Username" name="username" />
          <input required type="password" placeholder="Password" name="password" />
          <button type="submit">Sign In</button>
        </form>
      </div>
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <h1>Welcome Back!</h1>
            <p>To keep connected with us please login with your personal info</p>
            <button class="ghost" id="signIn">Sign In</button>
          </div>
          <div class="overlay-panel overlay-right">
            <h1>Himalayas</h1>
            <p>Enter your personal details and start journey with us</p>
            <button class="ghost" id="signUp">Sign Up</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <a href="{% url 'himalaya:home' %}"><i class="fa-solid fa-house fa-xl"></i></a>
    <a href="{% url 'himalaya:login_signup' %}"><i class="fa-solid fa-user fa-xl"></i></a>
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  <script src="{% static 'himalaya/login.js' %}"></script>
</body>
</html>

himalaya/templates/himalaya/tour.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Check out these places</title>
    <link rel="stylesheet" href="{% static 'himalaya/tour.css' %}">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css'>
</head>
<body>
    <center><h1>Tourism</h1></center>
  <section class="carousel" aria-label="Gallery">
    <ol class="carousel__viewport">
      <li id="carousel__slide1"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:bilaspur' %}" style="color: black;">Bilaspur</a>
          <a href="#carousel__slide10"
            class="carousel__prev">Go to last slide</a>
          <a href="#carousel__slide2"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide2"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:chamba' %}" style="color: black;">Chamba</a>
          <a href="#carousel__slide1"
            class="carousel__prev">Go to previous slide</a>
          <a href="#carousel__slide3"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide3"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:hamirpur' %}" style="color: black;">Hamirpur</a>
          <a href="#carousel__slide2"
            class="carousel__prev">Go to previous slide</a>
          <a href="#carousel__slide4"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide4"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:kangra' %}" style="color: white;">Kangra</a>
          <a href="#carousel__slide3"
            class="carousel__prev">Go to previous slide</a>
          <a href="#carousel__slide5"
            class="carousel__next">Go to first slide</a>
          </div>
      </li>
      <li id="carousel__slide5"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:kinnaur' %}" style="color: white;">Kinnaur</a>
          <a href="#carousel__slide4"
            class="carousel__prev">Go to last slide</a>
          <a href="#carousel__slide6"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide6"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:kullu' %}" style="color: white;">Kullu</a>
          <a href="#carousel__slide5"
            class="carousel__prev">Go to previous slide</a>
          <a href="#carousel__slide7"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide7"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:lahual_spiti' %}" style="color: white;">Lahual and Spiti</a>
          <a href="#carousel__slide6"
            class="carousel__prev">Go to last slide</a>
          <a href="#carousel__slide8"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide8"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:mandi' %}" style="color: black;">Mandi</a>
          <a href="#carousel__slide7"
            class="carousel__prev">Go to previous slide</a>
          <a href="#carousel__slide9"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide9"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:shimla' %}" style="color: white;">Shimla</a>
          <a href="#carousel__slide8"
            class="carousel__prev">Go to last slide</a>
          <a href="#carousel__slide10"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
      <li id="carousel__slide10"
          tabindex="0"
          class="carousel__slide">
        <div class="carousel__snapper">
          <a  class="place" href="{% url 'himalaya:una' %}" style="color: black;">Una</a>
          <a href="#carousel__slide9"
            class="carousel__prev">Go to previous slide</a>
          <a href="#carousel__slide1"
            class="carousel__next">Go to next slide</a>
        </div>
      </li>
    </ol>
    <aside class="carousel__navigation">
      <ol class="carousel__navigation-list">
        <li class="carousel__navigation-item">
          <a href="#carousel__slide1"
            class="carousel__navigation-button">Go to slide 1</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide2"
            class="carousel__navigation-button">Go to slide 2</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide3"
            class="carousel__navigation-button">Go to slide 3</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide4"
            class="carousel__navigation-button">Go to slide 4</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide5"
            class="carousel__navigation-button">Go to slide 5</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide6"
            class="carousel__navigation-button">Go to slide 6</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide7"
            class="carousel__navigation-button">Go to slide 7</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide8"
            class="carousel__navigation-button">Go to slide 8</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide9"
            class="carousel__navigation-button">Go to slide 9</a>
        </li>
        <li class="carousel__navigation-item">
          <a href="#carousel__slide10"
            class="carousel__navigation-button">Go to slide 10</a>
        </li>
      </ol>
    </aside>
  </section>
  <footer>
    <a href="{% url 'himalaya:home' %}"><i class="fa-solid fa-house fa-xl"></i></a>
    <a href="{% url 'himalaya:displayweather' %}"><i class="fa-solid fa-cloud-sun-rain fa-xl"></i></a>
    <a href="{% url 'himalaya:tourism' %}"><i class="fa-solid fa-person-hiking fa-xl"></i></a>
    <a href="{% url 'himalaya:displaytripplan' %}"><i class="fa-solid fa-plane-departure fa-xl"></i></a>
  </footer>
</body>
</html>

himalaya/templates/himalaya/weather.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather</title>
    <script src="https://kit.fontawesome.com/3121321f07.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'himalaya/weather.css' %}">
</head>
<body>
    <div class="container">
        <div class="left">
            <span class="header"><b>KNOW THE WEATHER</b></span><br>
            <span class="text"><p>Thinking of visiting somewhere</p><p>
            Check the weather so that it does not wash away your</p><p>idea</p></span>
            <form name="weatherdata" action="{% url 'himalaya:getweatherdata' %}" method="post">
                {% csrf_token %}
                <label class="label" for="date">Date</label>
                <input type="date" value="{{ today }}" max='{{ maxdate }}' name="date">
                <label class="label" for="place">Select city</label>
                <select name="place">
                    <option value="Shimla">Shimla</option>    
                    <option value="Bilaspur">Bilaspur</option>
                    <option value="Kangra">Kangra</option>
                    <option value="Kinnaur">Kinnaur</option>
                    <option selected value="Kullu">Kullu</option>
                    <option value="Lahaul">Lahaul</option>
                    <option value="Mandi">Mandi</option>
                    <option value="Srimaur">Srimaur</option>
                    <option value="Solan">Solan</option>
                    <option value="Una">Una</option>
                    <option value="Hamirpur">Hamirpur</option>
                    <option value="Chamba">Chamba</option>                    
                </select>
                <div class="buttonbox">
                    <button type="submit">Get weather</button>
                    <a href="{% url 'himalaya:home' %}"><button type="button">Home</button></a>
                </div>
            </form>
        </div>
        <div class="right">
            <div class="block">
                <span class="desc2">{% if forecast is not None %}{{ forecast.address }} {{ days.datetime }} {% endif %}</span><br>
                <span class="desc">Temperature</span><br>
                <i style="font-size: 35px;" class="fa-solid fa-temperature-half"> {% if forecast is not none %} {{ days.temp }} F{% endif %}</i><br>
            </div>
            <div class="block">
                <span class="desc">Max Temperature</span><br>
                <i style="font-size: 35px;" class="fa-solid fa-temperature-high">  {% if forecast is not none %} {{ days.tempmax }} F{% endif %}</i><br>
                <span class="desc">Min Temperature</span><br>
                <i style="font-size: 35px;" class="fa-solid fa-temperature-low">  {% if forecast is not none %} {{ days.tempmin }} F{% endif %}</i><br>
            </div>
            <div class="block">
                <span class="desc">Precipitation Chance</span><br>
                <i style="font-size: 25px;" class="fa-solid fa-cloud"> {% if forecast is not none %} {{ days.precipprob }} % {% endif %}</i><br>
                <span class="desc">Dew point</span><br>
                <img src="{% static 'himalaya/Images/dew.png' %}" style="width: 40px;"> <span style="font-size: 40px;" class="desc">{% if forecast is not none %} {{ days.dew }} F {% endif %}</span><br>
                
            </div>
            <div class="block">
                <span class="desc">Humidity</span><br>
                <img src="{% static 'himalaya/Images/humidity.png' %}" style="width: 40px;"><span style="font-size: 40px;" class="desc">    {% if forecast is not none %} {{ days.humidity }} % {% endif %}</span><br>
                <span class="desc">Feels Like:  {% if forecast is not none %} {{ days.feelslike }} F {% endif %}</span><br>
            </div>
            <div class="block">
                <span class="desc">Sunrise</span><br>
                <img src="{% static 'himalaya/Images/sunrise.png' %}" style="width: 40px;"><span style="font-size: 40px;" class="desc">  {% if forecast is not none %} {{ days.sunrise }} {% endif %}</span><br>
                <span class="desc">Sunset</span><br>
                <img src="{% static 'himalaya/Images/sunset.png' %}" style="width: 40px;"><span style="font-size: 40px;" class="desc">{% if forecast is not none %} {{ days.sunset }} {% endif %}</span><br>
            </div>
            <div class="block">
                <span class="desc"><b>Description:</b></span><br>
                <span class="desc"> {% if forecast is not none %} {{ days.description }} {% endif %}</span><br>
            </div>
        </div>
    </div>
</body>
</html>